sudo: required
language: csharp
mono:
  - 5.2.0
solution: QuantConnect.Lean.sln
install:
  - nuget restore QuantConnect.Lean.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release /p:VbcToolExe=vbnc.exe QuantConnect.Lean.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Tests/bin/Release/QuantConnect.Tests.dll --exclude:TravisExclude
after_success:
  - coveralls