sudo: required
language: csharp
mono:
  - 5.12.0
solution: QuantConnect.Lean.sln
before_install:
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - wget -q https://cdn.quantconnect.com/miniconda/Miniconda3-4.5.12-Linux-x86_64.sh
  - bash Miniconda3-4.5.12-Linux-x86_64.sh -b
  - rm -rf Miniconda3-4.5.12-Linux-x86_64.sh
  - sudo ln -s $HOME/miniconda3/lib/libpython3.6m.so /usr/lib/libpython3.6m.so
  - conda update -y python conda pip
  - conda install -y python=3.6.8
  - conda install -y numpy=1.18.1
  - conda install -y pandas=0.25.3
  - conda install -y cython=0.29.15
  - conda install -y scipy=1.4.1
  - conda install -y wrapt=1.12.1
install:
  - nuget restore QuantConnect.Lean.sln -v quiet
  - nuget install NUnit.Runners -Version 3.11.1 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release /p:VbcToolExe=vbnc.exe /v:quiet /p:WarningLevel=1 QuantConnect.Lean.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.11.1/tools/nunit3-console.exe ./Tests/bin/Release/QuantConnect.Tests.dll --where "cat != TravisExclude" --labels=Off --params:log-handler=ConsoleErrorLogHandler
  - chmod +x ci_build_stubs.sh
  - sudo -E ./ci_build_stubs.sh -d -t -g -p
