name: Build & Test Lean

on:
  push:
    branches: ['*']
    tags: ['*']
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures we fetch all history

      - name: Liberate disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          large-packages: false
          docker-images: false
          swap-storage: false

      - name: Define docker helper
        run: |
          echo -e 'runInContainer() { docker exec test-container "$@"; }\n' > "$HOME/ci_functions.sh"
          echo "BASH_ENV=$HOME/ci_functions.sh" >> $GITHUB_ENV

      - name: Start container
        run: |
          docker run -d \
            --workdir /__w/Lean/Lean \
            -v /home/runner/work:/__w \
            -e GITHUB_REF="${{ github.ref }}" \
            -e PYPI_API_TOKEN="${{ secrets.PYPI_API_TOKEN }}" \
            -e ADDITIONAL_STUBS_REPOS="${{ secrets.ADDITIONAL_STUBS_REPOS }}" \
            -e QC_GIT_TOKEN="${{ secrets.QC_GIT_TOKEN }}" \
            --name test-container \
            quantconnect/lean:foundation \
            tail -f /dev/null

      - name: Run build and tests
        run: |
          # Add exception
          runInContainer git config --global --add safe.directory /__w/Lean/Lean
          
          # Get Last Commit of the Current Tag
          TAG_COMMIT=$(runInContainer git rev-parse HEAD) && echo "CURRENT BRANCH LAST COMMIT $TAG_COMMIT"
          
          # Get Last Commit of the master
          MASTER_COMMIT=$(runInContainer git rev-parse origin/master) && echo "MASTER BRANCH LAST COMMIT $MASTER_COMMIT"
          
          # Build
          runInContainer dotnet build /p:Configuration=Release /v:quiet /p:WarningLevel=1 QuantConnect.Lean.sln
          
          # Run Tests
          runInContainer dotnet test ./Tests/bin/Release/QuantConnect.Tests.dll --blame-hang-timeout 300seconds --blame-crash --filter "TestCategory!=TravisExclude&TestCategory!=ResearchRegressionTests" -- TestRunParameters.Parameter\(name=\"log-handler\", value=\"ConsoleErrorLogHandler\"\)
          
          # Generate & Publish python stubs
          echo "GITHUB_REF ${{ github.ref }}"
          if [[ "${{ github.ref }}" = refs/tags/* && "$TAG_COMMIT" = "$MASTER_COMMIT" ]]; then 
            echo "Generating stubs"
            runInContainer chmod +x ci_build_stubs.sh
            runInContainer ./ci_build_stubs.sh -t -g -p
          else 
            echo "Skipping stub generation"
          fi
